### ISSUE TITLE
V1.3.0 breaks "compare changes" of header files

### ISSUE THREAD

**Issue by elliott-col** [AkiraMiyakoda/cppIncludeGuard#12]
The latest update (to V1.3.0) breaks "compare changes" under VSCode source control navigation.  It appears that .h files no longer show a diff view, rather each time "compare changes" is selected, the displayed file will alternate between `foo.h (git) (read-only)` and `foo.h`, with a diff view very briefly flashing into view.  Clicking on the file again while the diff view is being loaded sometimes causes a successful diff to be displayed.

Rolling this extension back to V1.2.1 resolves the problem.

**OS:** Windows 10

**VSCode version information:**
Version: 1.55.0 (user setup)
Commit: c185983a683d14c396952dd432459097bc7f757f
Date: 2021-03-30T16:01:55.261Z
Electron: 11.3.0
Chrome: 87.0.4280.141
Node.js: 12.18.3
V8: 8.7.220.31-electron.0
OS: Windows_NT x64 10.0.19042

**Comment by AkiraMiyakoda** [comment]
@HO-COOH 
Can you fix that? I am too busy now to locate and fix the issue.

**Comment by HO-COOH** [comment]
Thanks for pointing that out. Quite a small but serious issue. Now it should be good after it's merged

**Comment by AkiraMiyakoda** [comment]
@HO-COOH 
Thanks for quick work! Your fix has been published.
