### ISSUE TITLE
Include guard Skip setting does not work (at least on Windows)

### ISSUE THREAD

**Issue by uentity** [AkiraMiyakoda/cppIncludeGuard#16]
I'm using VS Code on Windows and changing folder skip setting (most useful for me) doesn't work -- nothing changes in generated guard.
At the same time folder Depth setting works correctly.

Maybe that is related to path delimiters?

**Comment by shilch** [comment]
Does not work on macOS either.

**Comment by shilch** [comment]
It looks like the issue is that the skip setting is only used if depth > 0 (https://github.com/AkiraMiyakoda/cppIncludeGuard/blob/master/src/commands.ts#L74). For me, the following settings work to skip the first path element:
```
    "C/C++ Include Guard.Path Skip": 1,
    "C/C++ Include Guard.Path Depth": 999999
```
