### ISSUE TITLE
[Feature Request] Allow automatic 'extern "C"' guard in header files

### ISSUE THREAD

**Issue by broddo** [AkiraMiyakoda/cppIncludeGuard#18]
Hi there,

I use your plugin all the time - its an incredibly useful tool. In one of my more recent projects, I realized I need to mix C and C++, so now I need to edit about 100 header files to add the extern C guard to C function prototypes, i.e.

```
#ifdef __cplusplus
extern "C" {
#endif

// List of C function prototypes

#ifdef __cplusplus
}
#endif
```

It struck me that your plugin would be the perfect place to accomplish such a think automatically - seeing as how you already have the mechanism constructed to surround code with include guards. 

What do you think? I would be willing to submit a pull request myself if time allows.

**Comment by AkiraMiyakoda** [comment]
Hi @broddo 
Thanks for your appreciation. 
However, I think that ```extern "C"``` is out of the scope of this extension. It looks similar to an include guard, but they are essentially different. I'd like to stick to the "do one thing well" approach. 
IMHO, it's more user-friendly to make separate extension to insert ```extern "C"```. You can safely utilize my mechanism when you create an extension yourself.

**Comment by broddo** [comment]
That makes sense @AkiraMiyakoda - thank's for taking the time to respond!
