### ISSUE TITLE
Allow to specify number of spaces between #endif and the comment

### ISSUE THREAD

**Issue by alexeyr** [AkiraMiyakoda/cppIncludeGuard#19]
For the project I am working on, it has to be 
```
#endif  // comment
```
with two spaces, the extension only allows one. Alternately, it could detect the number of spaces and not change it when updating the line, but then you still have to update it manually (or with Format Document, etc.) once.

**Comment by AkiraMiyakoda** [comment]
Thaks for the nice catch @alexeyr !
I have published the new version with the feature you suggested.
