### ISSUE TITLE
Command 'Insert C/C++ Include Guard' resulted in an error (command 'extension.insertIncludeGuard' not found)

### ISSUE THREAD

**Issue by MrPointer** [AkiraMiyakoda/cppIncludeGuard#5]
The title pretty much says it all 😆 

Anyway, here's my environment configuration for some additional insight:

**Host OS**: Windows 10 build 2004
**Remote Development**: SSH
**Remote OS**: Ubuntu 16.04 (It's actually a docker container, but it shouldn't matter)
**VSCode Version**: 1.46.1
**C/C++ Include Guard Version**: 1.0.0

And that's pretty much it - I haven't configured any settings yet, just opened a header file and hit the _'Insert C/C++ Include Guard'_ from the command palette.

**Comment by AkiraMiyakoda** [comment]
Thanks @MrPointer,
I have fixed the issue and published v1.0.1.
