### ISSUE TITLE
Option to not have trailing #endif comment.

### ISSUE THREAD

**Issue by mdx97** [AkiraMiyakoda/cppIncludeGuard#6]
Hello,

Love the project! It'd be great to see an option to not have any trailing comment on the #endif line, as I do not like doing this in my code, and I'm sure others are in the same boat.

Thanks!

**Comment by AkiraMiyakoda** [comment]
Nice proposal 👍 
Thanks!

**Comment by AkiraMiyakoda** [comment]
I've done it.
