### ISSUE TITLE
How to remove prefixes directory?

### ISSUE THREAD

**Issue by ultimaweapon** [AkiraMiyakoda/cppIncludeGuard#7]
Hello,

Let say I want to create include guard for this file: `src/db/db.hpp`

Want I want is something like this:

```cpp
#ifndef DB_DB_HPP
#define DB_DB_HPP
#endif
```

You will notice there is no `src` prefixes. I'm tried to adjust `C/C++ Include Guard.Path Depth` but I can't make it work. So my question is how to achieve this result?

**Comment by AkiraMiyakoda** [comment]
Hi @ultimaweapon,

Settings like below will realize what you want. 
Macro Type: Filepath
Path Depth: 1
![settings](https://user-images.githubusercontent.com/30318985/98079563-5b078500-1eb7-11eb-9b91-7beaf5ce8068.png)

**Comment by ultimaweapon** [comment]
Hi @AkiraMiyakoda,

Thank you for your response. I was tried your settings but it does not work. Here are my settings:

![Screenshot from 2020-11-04 14-18-39](https://user-images.githubusercontent.com/3048307/98080918-d01f8e00-1ea8-11eb-9bb0-8493991d4a88.png)

Here is the result for file `src/main.hpp`:

```cpp
#ifndef COUPON_REGISTRY_SRC_MAIN_HPP
#define COUPON_REGISTRY_SRC_MAIN_HPP

#include "options.hpp"

namespace coupon_registry {

	options const & current_options();

}

#endif
```

**Comment by HO-COOH** [comment]
@AkiraMiyakoda 's response a bit misleading I think.
@ultimaweapon If you want
```cpp
#ifndef DB_DB_HPP
#define DB_DB_HPP
#endif
``` 
in `src/db/db.hpp`, you should set `Path Depth` to `2` instead of `1`. The setting means how many level of folders "up" along the path.

![image](https://user-images.githubusercontent.com/42881734/111936049-ca5ec980-8a92-11eb-8ad3-0da210199542.png)


The left is set to `1`. The right is set to `2`.

**Comment by ultimaweapon** [comment]
@HO-COOH thank you for your response. I'm already working on another project that does not use C/C++ anymore so I will close this issue.
